# Generated by Django 4.0.6 on 2024-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
