# Generated by Django 4.0.6 on 2024-09-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_gym_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Caterer',
                'verbose_name_plural': 'Caterers',
            },
        ),
        migrations.CreateModel(
            name='CatererMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='partners.caterer')),
            ],
            options={
                'verbose_name': 'Caterer Menu',
                'verbose_name_plural': 'Caterer Menus',
            },
        ),
    ]
