# Generated by Django 4.0.6 on 2024-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_caterer_caterermenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterermenu',
            name='image',
            field=models.ImageField(default=1, upload_to='caterer_menus'),
            preserve_default=False,
        ),
    ]
