# Generated by Django 4.0.6 on 2024-09-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_full_name_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pro_user',
            field=models.BooleanField(default=False),
        ),
    ]
