# Generated by Django 4.0.6 on 2024-09-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_pro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pro_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_from',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_to',
        ),
    ]
