# Generated by Django 4.0.6 on 2024-09-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_gym_promo_code'),
        ('subscription', '0002_alter_plan_options_plan_days_count_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='partners.gym'),
        ),
    ]
