# Generated by Django 4.0.6 on 2024-09-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
    ]
